# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c1898f275144ccee1f98210ade0a926d7a5fc2b05b51a8ae2998cbf45944ba1fa58d71697c52f6af9c62eb59091b38d910f1bae38fb307b30d5641267c38166

test:
  secret_key_base: 42da3e449a6049b000ebe51a0a2d2b0991b78a68984448d5ad4bbd39680ef6784554573bbe9d4468c6b52c74b50a61148c594e22c0379a4b8306868b40cae409

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
